import AdmZip from "adm-zip";
import type { UnifiedDocument } from "../../shared/documentModel.js";
import type { ExportCenter } from "./exportCenter.js";
import { EXPORT_PRESETS } from "./exportPresets.js";

export function buildFullArchiveZip(document: UnifiedDocument, exportCenter: ExportCenter): Buffer {
  const zip = new AdmZip();
  zip.addFile("README.md", Buffer.from(readme(document), "utf8"));
  zip.addFile("document.json", Buffer.from(exportCenter.documentJson(document), "utf8"));
  zip.addFile("analysis.md", Buffer.from(exportCenter.analysisMarkdownFromDocument(document), "utf8"));
  zip.addFile("chat.md", Buffer.from(exportCenter.chatMarkdown(document, document.chatMessages ?? []), "utf8"));
  for (const preset of EXPORT_PRESETS) {
    zip.addFile(`${preset.id}.md`, Buffer.from(exportCenter.presetMarkdown(document, preset.id), "utf8"));
  }
  return zip.toBuffer();
}

function readme(document: UnifiedDocument): string {
  return [
    `# ${document.title} Export Archive`,
    "",
    "This archive was generated by DocuMuse Studio.",
    "",
    "Included files:",
    "",
    "- document.json",
    "- analysis.md",
    "- chat.md",
    "- study-notes.md",
    "- research-digest.md",
    "- presentation-outline.md",
    "- podcast-prep.md",
    "",
    "The archive does not include the original EPUB/PDF file, API keys, release artifacts, or temporary fixtures."
  ].join("\n");
}
